/*!
 * @file main.cpp
 * Application execution point
 * @author Peter Koprda (xkoprd00)
 * @author Adam Múdry (xmudry01)
 * @brief Main program
 */

#include "mainwindow.h"
#include <QApplication>

/*!
 * \brief Main program block, generated by Qt.
 * \param argc Argument count
 * \param argv Argument vector
 * \return 0 on success run, others on error
 */
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();
    return a.exec();
}
